### ISSUE TITLE
Result after pay with paypal adaptive

### ISSUE THREAD

**Issue by agusabrianto** [angelleye/paypal-codeigniter#26]
How to see result after login & pay with adaptive?
No callback?

Thanks.

**Comment by angelleye** [comment]
Adaptive is no longer available unless you're grandfathered into it.  If you're building a new solution now you will not want to use Adaptive because they aren't going to give you a live App ID.  

They will be introducing a new set of APIs called Marketplaces, but that is not available yet.  You may want to take a look at this article I wrote about an alternative while things are in limbo.

https://www.angelleye.com/paypal-split-payments-express-checkout-billing-agreements-reference-transactions/
